version: "3.2"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    volumes:
      - type: bind
        source: ./code
        target: /code
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf 
  php-fpm:
    image:  php:7.2-fpm
    volumes:
      - type: bind
        source: ./code
        target: /code
      # - type: bind
      #   source: ./www.conf
      #   target: /usr/local/etc/php-fpm.d/www.conf

